sudo: required
services:
  - docker

before_install:
  - docker build -t cwhite5/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cwhite5/react-test npm test

after_success:
  - docker build -t cwhite5/complex-client ./client
  - docker build -t cwhite5/complex-nginx ./nginx
  - docker build -t cwhite5/complex-server ./server
  - docker build -t cwhite5/complex-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
  # Take those images and push to dockerhub
  - docker push cwhite5/complex-client
  - docker push cwhite5/complex-nginx
  - docker push cwhite5/complex-server
  - docker push cwhite5/complex-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "complex-docker"
  env: "ComplexDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-047401370718"
  bucket_path: "complex-docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true
